.TH "Cell" 3 "Tue Apr 26 2022" "hash table PROJECT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cell
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "struct \fBCell\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBCell\fP * \fBprev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* Cell::data"

.SS "struct \fBCell\fP* Cell::next"

.SS "struct \fBCell\fP * Cell::prev"


.SH "Author"
.PP 
Generated automatically by Doxygen for hash table PROJECT from the source code\&.
