.TH "/home/ubuntu20/Bureau/TD5_avance/cmake_avance__IDE___DOXYFILES/demo/example.c" 3 "Tue Apr 26 2022" "hash table PROJECT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ubuntu20/Bureau/TD5_avance/cmake_avance__IDE___DOXYFILES/demo/example.c
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'hash\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBstr_hash\fP (unsigned char *str)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "main main program "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
main main program 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP program argument counter 
.br
\fIargv\fP array of arguments 
.RE
.PP
\fBReturns\fP
.RS 4
0 if everything ok 
.RE
.PP

.SS "int str_hash (unsigned char * str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for hash table PROJECT from the source code\&.
