.TH "/home/ubuntu20/Bureau/TD5_avance/cmake_avance__IDE___DOXYFILES/hash/hash.h" 3 "Tue Apr 26 2022" "hash table PROJECT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ubuntu20/Bureau/TD5_avance/cmake_avance__IDE___DOXYFILES/hash/hash.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBCell\fP * \fBhash_newcell\fP (void *data)"
.br
.ti -1c
.RI "struct \fBhash_Table\fP * \fBhash_init\fP (int(*cmp)(void *, void *), int(*hash)(void *))"
.br
.ti -1c
.RI "int \fBhash_add\fP (struct \fBhash_Table\fP *hash, void *data)"
.br
.RI "hash_add a new data into the hash table "
.ti -1c
.RI "int \fBhash_cherche\fP (struct \fBhash_Table\fP *hash, void *data)"
.br
.ti -1c
.RI "void \fBhash_free\fP (struct \fBhash_Table\fP *hash, void(*release)(void *))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int hash_add (struct \fBhash_Table\fP * hash, void * data)"

.PP
hash_add a new data into the hash table 
.PP
\fBParameters\fP
.RS 4
\fIhash\fP 
.br
\fIdata\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "int hash_cherche (struct \fBhash_Table\fP * hash, void * data)"

.SS "void hash_free (struct \fBhash_Table\fP * hash, void(*)(void *) release)"

.SS "struct \fBhash_Table\fP* hash_init (int(*)(void *, void *) cmp, int(*)(void *) hash)"

.SS "struct \fBCell\fP* hash_newcell (void * data)"

.SH "Author"
.PP 
Generated automatically by Doxygen for hash table PROJECT from the source code\&.
